---
title: "Numeracy, Modelling and Data Management"
author: "Mike Spencer"
date: "27/03/2015"
output:
  html_document:
    highlight: tango
    theme: united
    toc: yes
---

## Introduction

Welcome to the final session of the doctoral training course: numeracy, modelling and data management. This course was originally scheduled to cover [GDAL](http://www.gdal.org/), and it will, but as it has been postponed by a week we've decided to include a general wrap up of the course and show some example work flows.

### This document

This document has been written using [R markdown](http://rmarkdown.rstudio.com/), which I understand Mark Naylor showed you. R markdown is similar to [Python notebooks](http://ipython.org/notebook.html), both of which allow you to write documents and embed code and results within them. R markdown can write output to html, pdf or word formats. R markdown works best for me as an electronic lab notebook, so all my analysis happens within R markdown and I write comments on what I find as I go along. This way, when you're writing that Nature paper and come back to find the code that generated your plot, it's all available within the same document. Your hunting will be vastly reduced!

Writing in markdown is really simple, plain text is just plain text. Here's a handy cheat sheet for headings and highlighting: http://blog.rstudio.org/2014/08/01/the-r-markdown-cheat-sheet/. If you want to do something more complicated it will happily accept html code (if that's what you're wrapping it to) or LaTeX. The easiest way to write in R markdown is using the R IDE [RStudio](http://www.rstudio.com/products/rstudio/download/), this is freely available for Linux, Windows and Mac. It's also installed on the school server, burn, open it by typing *rstudio* in a terminal.

This R markdown html is hosted as a github page, you can view the repository here: https://github.com/mikerspencer/training/tree/gh-pages which also includes the raw markdown file (Rmd) this webpage is based on.

I'm going to cover a few things in this session and talk about specific tools, these are the ones I use. They're certainly not the only ones available, but they are what I know. If you'd like to talk about other options, advantages and disadvantages drop by and see me in the Grant (rm 400) or [email](http://www.ed.ac.uk/schools-departments/geosciences/people?indv=2920&cw_xml=student.html). So here's what I'll cover:

* Backups (rsync)
* Version control (git)
* Command line (bash)
* Programming (R)
* Spatial data
      + GIS (QGIS, GRASS)
      + GDAL (R, GIS)
      + Programming (R)
* Writing (markdown & LaTeX)

The key, for me, from these tools is that they help to make your research repeatable. This is really important holistically, but even on a personal level; if you need to make a few changes to a graph, table, paper... then all your analysis can be repeated with the click of a button - you don't have to remember it all in your head!

## Backups

Backing up your work is crucial. If you lose everything pity from your colleagues will not help get it back. Hopefully most of you will be working on the school server (adder/m drive), this is backed up. Another option could be that you work on your desktop and backup to the work server. If you do this copying folders across is so 1995. Use backup software like [rsync](http://en.wikipedia.org/wiki/Rsync) which scans for changes in files and only copies over what is needed. It's very fast. Here's an example that you would run in a bash terminal:

```{r backup, engine="bash", eval=F}
sudo rsync --delete --exclude='/.*/' --exclude='/dir/temp/' -azv -e ssh /home/s1066252 s1066252@adder.geos.ed.ac.uk:/home/s1066252/
```

The above example